# 01 Basic Tradeoff Plots

Recall/latency and IO/latency tradeoffs.

# 說明

本 notebook 產生 recall/latency 與系統指標的 tradeoff 圖表與摘要表，並輸出 Pareto frontier。

## 主要輸入
- `tables/filtered_stats.csv`（存在時優先）

## 主要輸出
- `figures/recall_vs_*`
- `tables/pareto_recall_latency.csv`
- `tables/tradeoff_by_params.csv`
- `tables/latency_correlation_*.csv`

## 合理性檢查建議
- Pareto frontier 點數應合理（不為 0）
- 不同 K 的分析需用 `FILTER_SEARCH_K` 控制一致性

In [1]:
# 匯入所需的套件
from pathlib import Path  # 用於處理檔案路徑
import os  # 用於存取環境變數
import re  # 用於正規表達式字串比對
import pandas as pd  # 用於資料表處理
from analysis_utils import normalize_columns
import numpy as np  # 用於數值運算

# 設定分析資料夾的路徑（轉為絕對路徑）
ANALYZE_DIR = Path('../outputFiles/analyze').resolve()

# 從環境變數取得報告前綴，預設為 'analysis_reports'
REPORT_PREFIX = os.environ.get('REPORT_PREFIX', 'analysis_reports')
# 從環境變數取得收集資料前綴，預設使用 REPORT_PREFIX 的值
COLLECT_PREFIX = os.environ.get('COLLECT_PREFIX', REPORT_PREFIX)

# 設定報告輸出資料夾路徑
REPORT_DIR = (ANALYZE_DIR / REPORT_PREFIX)
# 設定收集資料的資料夾路徑
COLLECT_DIR = (ANALYZE_DIR / COLLECT_PREFIX)

# 可手動指定統計資料 CSV 檔案路徑（若為 None 則自動尋找最新檔案）
STATS_CSV = None
# 可手動指定 Top-K 資料 CSV 檔案路徑（若為 None 則自動尋找最新檔案）
TOPK_CSV = None

# 圖表繪製設定
PLOT_MAX_POINTS = int(os.environ.get('PLOT_MAX_POINTS', '20000'))  # 最大繪圖點數（避免過密）
PLOT_ALPHA = float(os.environ.get('PLOT_ALPHA', '0.4'))  # 點的透明度（0-1）
PLOT_LOG_LATENCY = os.environ.get('PLOT_LOG_LATENCY', '1') != '0'  # 延遲是否使用對數刻度

# 召回率欄位名稱
RECALL_COL = 'recall_mean'

# 延遲欄位優先順序清單（按優先順序排列）
LATENCY_PRI_COLS = [
    'latency_p99_us',  # 延遲 99 百分位數（最常用）
    'latency_p95_us',  # 延遲 95 百分位數
    'latency_p50_us',  # 延遲中位數
    'mean_latency_us',  # 平均延遲
    'latency_p0_us',  # 最小延遲
    'latency_p999_us',  # 延遲 99.9 百分位數
]

# 過濾特定 search_K 值的資料（預設為 10）
FILTER_SEARCH_K = os.environ.get('FILTER_SEARCH_K', '10')

# 顏色編碼候選參數（用於圖表中以顏色區分不同參數值）
COLOR_CANDIDATES = ['search_W', 'search_L', 'search_T', 'build_R', 'build_L', 'cache_size']

# 要分析的權衡（tradeoff）特徵清單
TRADEOFF_FEATURES = [
    'ios_p99',  # I/O 次數 99 百分位數
    'queue_depth_p99',  # 佇列深度 99 百分位數
    'io_us_p99',  # I/O 時間 99 百分位數
    'cpu_us_p99',  # CPU 時間 99 百分位數
    'thread_util_p99',  # 執行緒使用率 99 百分位數
    'expanded_revisit_ratio',  # 擴展重訪比例
    'node_counts_top10_share',  # 前 10 節點的佔比
    'out_degree_p99',  # 節點出度 99 百分位數
    'out_degree_p0', # 節點出度最小值
    'iostat_aqu-sz_mean',  # I/O 統計平均佇列大小˙
]

def pick_latest(pattern):
    """
    從 COLLECT_DIR 資料夾中找出符合 pattern 的最新檔案
    
    參數：
        pattern: 檔案名稱的搜尋模式（glob pattern）
    
    回傳：
        最新的檔案路徑（依據檔案名稱排序）
    """
    # 列出所有符合模式的檔案並排序
    files = sorted(COLLECT_DIR.glob(pattern))
    if not files:
        # 若沒有找到任何檔案，拋出錯誤
        raise FileNotFoundError(f'No files matched: {pattern}')
    # 回傳最後一個（最新的）檔案
    return files[-1]

def downsample_df(df, max_points=PLOT_MAX_POINTS, seed=42):
    """
    降採樣資料表（避免繪圖點數過多）
    
    參數：
        df: 原始資料表
        max_points: 最大保留點數
        seed: 隨機種子（確保結果可重現）
    
    回傳：
        降採樣後的資料表
    """
    if len(df) <= max_points:
        # 若資料量已小於限制，直接回傳
        return df
    # 隨機抽樣指定數量的資料點
    return df.sample(n=max_points, random_state=seed)

def safe_scatter(df, x, y, color=None, title=None, out_path=None, cmap='viridis'):
    """
    安全的散佈圖繪製函數（自動處理缺失欄位與空資料）
    
    參數：
        df: 資料表
        x: X 軸欄位名稱
        y: Y 軸欄位名稱
        color: 顏色編碼欄位名稱（可選）
        title: 圖表標題（可選）
        out_path: 輸出檔案路徑（可選）
        cmap: 色彩映射（預設為 'viridis'）
    """
    # 檢查必要欄位是否存在
    if x not in df.columns or y not in df.columns:
        print('skip scatter missing columns:', x, y)
        return
    
    # 準備要繪製的欄位清單
    cols = [x, y] + ([color] if color and color in df.columns else [])
    # 移除有遺失值的列
    plot_df = df[cols].dropna()
    
    if plot_df.empty:
        print('skip scatter empty data:', x, y)
        return
    
    # 降採樣（避免點數過多）
    plot_df = downsample_df(plot_df)
    
    # 繪製散佈圖
    ax = plot_df.plot.scatter(
        x=x,
        y=y,
        c=color if color in plot_df.columns else None,  # 顏色編碼
        cmap=cmap,  # 色彩映射
        alpha=PLOT_ALPHA,  # 透明度
        figsize=(6, 4),  # 圖表大小
    )
    
    # 設定標題
    if title:
        ax.set_title(title)
    
    # 若 Y 軸是延遲指標且啟用對數刻度，則使用對數刻度
    if PLOT_LOG_LATENCY and y.endswith('_us'):
        ax.set_yscale('log')
    
    # 匯入繪圖套件
    import matplotlib.pyplot as plt
    # 自動調整佈局
    plt.tight_layout()
    
    # 若有指定輸出路徑，則儲存圖表
    if out_path:
        plt.savefig(out_path, dpi=150)
    
    # 關閉圖表釋放記憶體
    plt.close()

def pareto_frontier(df, recall_col, latency_col):
    """
    計算 Pareto frontier（帕雷托前沿）
    找出在 recall/latency 權衡中無法被改善的最佳配置點
    
    參數：
        df: 資料表
        recall_col: 召回率欄位名稱
        latency_col: 延遲欄位名稱
    
    回傳：
        Pareto frontier 上的資料點
    """
    # 檢查必要欄位是否存在
    if recall_col not in df.columns or latency_col not in df.columns:
        return pd.DataFrame()
    
    # 取出需要的欄位並移除遺失值
    subset = df[[recall_col, latency_col, 'run_prefix']].dropna().copy()
    
    if subset.empty:
        return pd.DataFrame()
    
    # 依 recall 由高到低排序
    subset = subset.sort_values(recall_col, ascending=False)
    
    # 追蹤目前最佳的延遲
    best_latency = np.inf
    keep = []  # 保留的 Pareto 點索引
    
    # 掃描所有資料點
    for idx, row in subset.iterrows():
        # 若該點的延遲比目前最佳延遲更低，則加入 Pareto frontier
        if row[latency_col] < best_latency:
            keep.append(idx)
            best_latency = row[latency_col]
    
    # 回傳 Pareto frontier 上的點（依 recall 排序）
    return subset.loc[keep].sort_values(recall_col)

# 決定要載入的統計資料 CSV 檔案路徑
stats_path = Path(STATS_CSV) if STATS_CSV else pick_latest('collected_all_*.csv')
# 決定要載入的 Top-K 資料 CSV 檔案路徑
topk_path = stats_path

# 顯示即將載入的檔案路徑
print('stats:', stats_path)
print('topk :', topk_path)

# 讀取統計資料 CSV 檔案
stats_df = pd.read_csv(stats_path)
stats_df = normalize_columns(stats_df)
# 讀取 Top-K 資料 CSV 檔案
topk_df = stats_df[[c for c in stats_df.columns if c == 'run_prefix' or c.startswith('topk_')]].copy()

stats: /home/gt/research/DiskANN/scripts/paramAnalysis/gridSearch/outputFiles/analyze/siftsmall01/collected_all_siftsmall01_20260115_183457.csv
topk : /home/gt/research/DiskANN/scripts/paramAnalysis/gridSearch/outputFiles/analyze/siftsmall01/collected_all_siftsmall01_20260115_183457.csv

In [2]:
# ===== 合併 stats 和 topk 資料 =====

# 先複製統計資料作為基礎
merged = stats_df.copy()

# 若兩個資料表都有 run_prefix 欄位，則進行合併
if 'run_prefix' in stats_df.columns and 'run_prefix' in topk_df.columns:
    # 使用 left join 合併（保留所有 stats 的資料）
    # suffixes 參數處理重複欄位名稱：stats 的保持原名，topk 的加上 '_topk' 後綴
    merged = stats_df.merge(topk_df, on='run_prefix', how='left', suffixes=('', '_topk'))
else:
    print('skip merge: run_prefix missing')

# 顯示合併後的前幾列資料
merged.head()

,id,dataset_name,data_type,build_R,build_L,build_B,build_M,search_K,search_L,search_W,...,topk_degree_p1_topk,topk_degree_p5_topk,topk_degree_p10_topk,topk_degree_p25_topk,topk_degree_p50_topk,topk_degree_p75_topk,topk_degree_p90_topk,topk_degree_p95_topk,topk_degree_p99_topk,topk_degree_p100_topk
0,1,siftsmall,float,128,256,2.0,2.0,10,10,2,...,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0
1,2,siftsmall,float,128,256,2.0,2.0,10,10,2,...,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0
2,3,siftsmall,float,128,256,2.0,2.0,10,10,2,...,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0
3,4,siftsmall,float,128,256,2.0,2.0,10,10,2,...,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0
4,5,siftsmall,float,128,256,2.0,2.0,10,10,2,...,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0,128.0

In [3]:
# ===== 載入經過品質檢查過濾後的資料集（若存在） =====

# 嘗試載入 filtered_stats.csv（由前一個 notebook 產生）
filtered_path = (REPORT_DIR / 'tables' / 'filtered_stats.csv')
filtered_df = None

if filtered_path.exists():
    # 若檔案存在，則讀取
    filtered_df = pd.read_csv(filtered_path)
    print('filtered:', filtered_path)
else:
    print('filtered not found:', filtered_path)

# 決定要使用的基礎資料集（優先使用過濾後的資料）
base_df = filtered_df if filtered_df is not None else merged

def apply_search_k_filter(df, value):
    """
    過濾特定 search_K 值的資料
    
    參數：
        df: 資料表
        value: 要過濾的 search_K 值（字串）
    
    回傳：
        過濾後的資料表
    """
    # 若未指定值或欄位不存在，則不過濾
    if not value or 'search_K' not in df.columns:
        return df
    try:
        # 將字串轉為整數
        target = int(value)
    except ValueError:
        # 轉換失敗則不過濾
        return df
    # 回傳符合條件的資料
    return df[df['search_K'] == target].copy()

# 對所有資料集套用 search_K 過濾
base_df = apply_search_k_filter(base_df, FILTER_SEARCH_K)
merged = apply_search_k_filter(merged, FILTER_SEARCH_K)
if filtered_df is not None:
    filtered_df = apply_search_k_filter(filtered_df, FILTER_SEARCH_K)

# 找出可用的延遲欄位（依優先順序）
latency_cols = [c for c in LATENCY_PRI_COLS if c in base_df.columns]

# 若優先清單中沒有找到，則尋找所有延遲相關欄位
if not latency_cols:
    latency_cols = [c for c in base_df.columns if c.startswith('latency_') and c.endswith('_us')]

# 選擇主要的延遲欄位（清單中的第一個）
latency_primary = latency_cols[0] if latency_cols else None

# 顯示基礎資料集的資訊
print('base_df rows:', len(base_df))
print('latency cols:', latency_cols)

# 從候選清單中找出第一個存在的欄位作為顏色編碼
color_col = next((c for c in COLOR_CANDIDATES if c in base_df.columns), None)
print('color column:', color_col)

filtered: /home/gt/research/DiskANN/scripts/paramAnalysis/gridSearch/outputFiles/analyze/siftsmall01/tables/filtered_stats.csv
base_df rows: 1575
latency cols: ['latency_p99_us', 'latency_p95_us', 'latency_p50_us', 'latency_p999_us']
color column: search_W

In [4]:
# ===== 產生基本的 Recall vs Latency 散佈圖 =====

# 匯入繪圖套件
import matplotlib.pyplot as plt

# 建立圖表輸出資料夾
fig_dir = (REPORT_DIR / 'figures')
fig_dir.mkdir(parents=True, exist_ok=True)

# 為每個延遲欄位產生圖表
for lat in latency_cols:
    # 使用原始合併資料繪製（標記為 'raw'）
    safe_scatter(
        merged,
        RECALL_COL,  # X 軸：召回率
        lat,  # Y 軸：延遲
        color=color_col,  # 顏色編碼（如 search_W）
        title=f'Recall vs {lat} (raw)',
        out_path=fig_dir / f'recall_vs_{lat}_raw.png',
    )
    
    # 若有過濾後的資料，也產生過濾版本的圖表
    if filtered_df is not None:
        safe_scatter(
            filtered_df,
            RECALL_COL,
            lat,
            color=color_col,
            title=f'Recall vs {lat} (filtered)',
            out_path=fig_dir / f'recall_vs_{lat}_filtered.png',
        )

# 顯示儲存訊息
print('Saved figures to', fig_dir)

Saved figures to /home/gt/research/DiskANN/scripts/paramAnalysis/gridSearch/outputFiles/analyze/siftsmall01/figures

In [5]:
# ===== 產生以各參數為顏色編碼的 Recall vs Latency 圖表 =====

# 為每個候選參數產生個別的圖表，以了解不同參數對效能的影響
for param in COLOR_CANDIDATES:
    # 檢查該參數是否存在於資料中
    if param not in base_df.columns:
        continue
    
    # 為每個延遲欄位產生圖表
    for lat in latency_cols:
        # 繪製散佈圖，以該參數的值作為顏色編碼
        safe_scatter(
            base_df,
            RECALL_COL,  # X 軸：召回率
            lat,  # Y 軸：延遲
            color=param,  # 顏色編碼：該參數的值（如 search_W=16,32,64 會顯示不同顏色）
            title=f'Recall vs {lat} (by {param})',
            out_path=fig_dir / f'recall_vs_{lat}_by_{param}.png',
        )

# 顯示儲存訊息
print('Saved parameter-specific figures to', fig_dir)

Saved parameter-specific figures to /home/gt/research/DiskANN/scripts/paramAnalysis/gridSearch/outputFiles/analyze/siftsmall01/figures

In [6]:
# ===== 分組分析：固定建構/快取參數，觀察搜尋參數的影響 =====

# 定義分組的鍵值（建構參數和快取大小）
GROUP_KEYS = [c for c in ['build_R','build_L','build_B','build_M','cache_size'] if c in base_df.columns]

# 分組最小資料量門檻（避免樣本數太少的群組）
GROUP_MIN_SIZE = int(os.environ.get('GROUP_MIN_SIZE', '5'))

# 群組內要分析的顏色編碼參數（包含搜尋參數和建構參數）
GROUP_COLOR_PARAMS = ['search_W','search_L','search_T','search_K','build_R','build_L','cache_size']

# 若有分組鍵且有主要延遲欄位，則進行分組分析
if GROUP_KEYS and latency_primary is not None:
    # 依建構/快取參數組合進行分組
    for grp_vals, grp_df in base_df.groupby(GROUP_KEYS):
        # 跳過資料量不足的群組
        if len(grp_df) < GROUP_MIN_SIZE:
            continue
        
        # 處理單一分組鍵的情況（轉為 tuple）
        if not isinstance(grp_vals, tuple):
            grp_vals = (grp_vals,)
        
        # 建立群組標籤（如 'build_R=32_build_L=100_cache_size=1000'）
        label_parts = [f"{k}={v}" for k, v in zip(GROUP_KEYS, grp_vals)]
        grp_label = '_'.join(label_parts)
        
        # 為每個顏色編碼參數產生圖表
        for param in GROUP_COLOR_PARAMS:
            # 跳過不存在或值過少（無變化）的參數
            if param not in grp_df.columns or grp_df[param].nunique() < 2:
                continue
            
            # 繪製該群組的 Recall vs Latency 圖表
            safe_scatter(
                grp_df,
                RECALL_COL,
                latency_primary,
                color=param,  # 以該參數值標示顏色
                title=f'{grp_label}: Recall vs {latency_primary} (by {param})',
                out_path=fig_dir / f'recall_vs_{latency_primary}_{grp_label}_by_{param}.png',
            )

In [7]:
# ===== 產生系統指標 vs Latency 的權衡圖表 =====

# 匯入繪圖套件
import matplotlib.pyplot as plt

# 確保圖表輸出資料夾存在
fig_dir = (REPORT_DIR / 'figures')
fig_dir.mkdir(parents=True, exist_ok=True)

# 為每個系統指標與延遲組合產生圖表
for feat in TRADEOFF_FEATURES:
    for lat in latency_cols:
        # 繪製原始資料的圖表
        safe_scatter(
            merged,
            feat,  # X 軸：系統指標（如 ios_p99、queue_depth_p99）
            lat,  # Y 軸：延遲
            color=color_col,  # 顏色編碼
            title=f'{feat} vs {lat} (raw)',
            out_path=fig_dir / f'{feat}_vs_{lat}_raw.png',
            cmap='plasma',  # 使用 'plasma' 色彩映射
        )
        
        # 若有過濾後的資料，也產生過濾版本
        if filtered_df is not None:
            safe_scatter(
                filtered_df,
                feat,
                lat,
                color=color_col,
                title=f'{feat} vs {lat} (filtered)',
                out_path=fig_dir / f'{feat}_vs_{lat}_filtered.png',
                cmap='plasma',
            )

# 為每個系統指標產生 Recall vs 指標的圖表
for feat in TRADEOFF_FEATURES:
    safe_scatter(
        base_df,
        RECALL_COL,  # X 軸：召回率
        feat,  # Y 軸：系統指標
        color=color_col,
        title=f'Recall vs {feat}',
        out_path=fig_dir / f'recall_vs_{feat}.png',
        cmap='magma',  # 使用 'magma' 色彩映射
    )

# 顯示儲存訊息
print('Saved figures to', fig_dir)

Saved figures to /home/gt/research/DiskANN/scripts/paramAnalysis/gridSearch/outputFiles/analyze/siftsmall01/figures

In [8]:
# ===== 計算並視覺化 Pareto frontier（帕雷托前沿） =====

# 建立表格輸出資料夾
out_tables = (REPORT_DIR / 'tables')
out_tables.mkdir(parents=True, exist_ok=True)

# 檢查是否有可用的延遲欄位
if latency_primary is None:
    print('No latency column available for Pareto frontier')
    frontier_df = pd.DataFrame()
else:
    # 計算 Pareto frontier（找出在 recall/latency 權衡中無法被改善的點）
    frontier_df = pareto_frontier(base_df, RECALL_COL, latency_primary)

# 若有找到 Pareto frontier 點，則儲存並視覺化
if not frontier_df.empty:
    # 儲存 Pareto frontier 資料
    frontier_df.to_csv(out_tables / 'pareto_recall_latency.csv', index=False)
    
    # 準備繪圖資料（移除遺失值並降採樣）
    plot_df = base_df[[RECALL_COL, latency_primary]].dropna()
    plot_df = downsample_df(plot_df)
    
    # 匯入繪圖套件
    import matplotlib.pyplot as plt
    
    # 建立圖表
    plt.figure(figsize=(6, 4))
    
    # 繪製所有資料點（灰色散佈點）
    plt.scatter(plot_df[RECALL_COL], plot_df[latency_primary], s=10, alpha=PLOT_ALPHA)
    
    # 繪製 Pareto frontier 線（紅色粗線）
    plt.plot(frontier_df[RECALL_COL], frontier_df[latency_primary], color='#d62728', linewidth=2)
    
    # 設定標題和軸標籤
    plt.title('Recall vs Latency with Pareto Frontier')
    plt.xlabel(RECALL_COL)
    plt.ylabel(latency_primary)
    
    # 若啟用對數刻度，套用到 Y 軸
    if PLOT_LOG_LATENCY:
        plt.yscale('log')
    
    # 自動調整佈局
    plt.tight_layout()
    
    # 儲存圖表
    plt.savefig(REPORT_DIR / 'figures' / f'recall_vs_{latency_primary}_with_frontier.png', dpi=150)
    
    # 關閉圖表釋放記憶體
    plt.close()
else:
    print('Pareto frontier not available')

In [9]:
# ===== 產生彙總的權衡分析表格 =====

# 定義參數欄位清單
param_cols = [
    'build_R','build_L','build_B','build_M',  # 建構參數
    'search_K','search_L','search_W','search_T','cache_size',  # 搜尋參數與快取
]

# 只保留存在的欄位
param_cols = [c for c in param_cols if c in base_df.columns]

# 定義要彙總的指標（召回率 + 所有延遲欄位）
metrics = [c for c in [RECALL_COL] + latency_cols if c in base_df.columns]

# 初始化權衡表
tradeoff_by_params = pd.DataFrame()

# 若有參數和指標，則進行分組彙總
if param_cols and metrics:
    # 定義彙總方式：對每個指標計算中位數、平均值、最小值、最大值
    agg_map = {m: ['median', 'mean', 'min', 'max'] for m in metrics}
    
    # 依參數組合分組並彙總
    tradeoff_by_params = base_df.groupby(param_cols).agg(agg_map)
    
    # 將多層欄位名稱展平（如 'recall_mean_median'）
    tradeoff_by_params.columns = ['_'.join(col).strip() for col in tradeoff_by_params.columns]
    
    # 加上每個參數組合的資料筆數
    tradeoff_by_params['count'] = base_df.groupby(param_cols).size().values
    
    # 重設索引（讓參數欄位變回一般欄位）
    tradeoff_by_params = tradeoff_by_params.reset_index()
    
    # 依資料筆數由多到少排序
    tradeoff_by_params = tradeoff_by_params.sort_values('count', ascending=False)
    
    # 儲存表格
    tradeoff_by_params.to_csv(out_tables / 'tradeoff_by_params.csv', index=False)

# 若有召回率和主要延遲欄位，建立召回率分箱摘要表
if RECALL_COL in base_df.columns and latency_primary is not None:
    # 將召回率範圍分成 10 個區間
    bins = np.linspace(base_df[RECALL_COL].min(), base_df[RECALL_COL].max(), 11)
    
    # 複製資料並加上召回率分箱欄位
    recall_bins = base_df.copy()
    recall_bins['recall_bin'] = pd.cut(recall_bins[RECALL_COL], bins=bins, include_lowest=True)
    
    # 依召回率區間分組，計算延遲的統計值
    recall_bin_summary = (
        recall_bins.groupby('recall_bin')[[latency_primary]]
        .agg(['median','mean','min','max','count'])  # 計算中位數、平均值、最小值、最大值、筆數
        .reset_index()
    )
    
    # 設定欄位名稱
    recall_bin_summary.columns = [
        'recall_bin',
        'latency_median','latency_mean','latency_min','latency_max','count',
    ]
    
    # 儲存表格
    recall_bin_summary.to_csv(out_tables / f'tradeoff_recall_bins_{latency_primary}.csv', index=False)

# 顯示前 5 列權衡表
tradeoff_by_params.head(5)

/tmp/ipykernel_221170/2630696085.py:52: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  recall_bins.groupby('recall_bin')[[latency_primary]]

,build_R,build_L,build_B,build_M,search_K,search_L,search_W,search_T,recall_mean_median,recall_mean_mean,...,latency_p95_us_max,latency_p50_us_median,latency_p50_us_mean,latency_p50_us_min,latency_p50_us_max,latency_p999_us_median,latency_p999_us_mean,latency_p999_us_min,latency_p999_us_max,count
0,16,32,2.0,2.0,10,10,1,1,0.931,0.931,...,3113.3181,1676.429,1793.185473,1522.941,2273.2061,2813.3970,2873.952800,2355.6899,3834.1680,15
1,16,32,2.0,2.0,10,10,1,4,0.931,0.931,...,1137.7800,741.168,756.412600,657.150,879.2060,1028.0439,1043.725127,974.7040,1189.7980,15
2,16,32,2.0,2.0,10,10,1,16,0.931,0.931,...,2147.4800,850.713,851.064467,741.939,994.2410,1300.8450,1339.786073,1151.9860,2244.6819,15
3,16,32,2.0,2.0,10,10,2,1,0.947,0.947,...,1834.3040,810.227,791.190533,556.231,1103.0250,1528.2010,1647.786587,967.1400,2374.7849,15
4,16,32,2.0,2.0,10,10,2,4,0.947,0.947,...,880.0270,479.127,513.364400,441.256,641.9120,843.6190,863.134333,751.7580,1082.2960,15

In [10]:
# ===== 計算各特徵與延遲的相關性分析 =====

# 初始化相關性表
corr_df = pd.DataFrame()

# 若有主要延遲欄位，則進行相關性分析
if latency_primary is not None and latency_primary in base_df.columns:
    # 找出所有數值型欄位
    num_cols = [c for c in base_df.columns if pd.api.types.is_numeric_dtype(base_df[c])]
    
    # 儲存相關性結果
    rows = []
    
    # 對每個數值欄位計算與延遲的相關性
    for col in num_cols:
        # 跳過延遲欄位本身
        if col == latency_primary:
            continue
        
        # 取出該欄位與延遲欄位的資料（移除遺失值）
        series = base_df[[col, latency_primary]].dropna()
        
        if series.empty:
            continue
        
        # 計算 Pearson 相關係數（線性相關性，範圍 -1 到 1）
        pearson = series[col].corr(series[latency_primary], method='pearson')
        
        # 計算 Spearman 相關係數（單調相關性，對非線性關係更穩健）
        spearman = series[col].corr(series[latency_primary], method='spearman')
        
        # 記錄結果
        rows.append({
            'feature': col,  # 特徵名稱
            'pearson': pearson,  # Pearson 相關係數
            'spearman': spearman,  # Spearman 相關係數
            'count': len(series),  # 有效資料筆數
        })
    
    # 建立相關性表格並依 Spearman 係數排序（由高到低）
    corr_df = pd.DataFrame(rows).sort_values('spearman', ascending=False)
    
    # 儲存表格
    corr_df.to_csv(out_tables / f'latency_correlation_{latency_primary}.csv', index=False)

# 顯示相關性最高的前 10 個特徵
corr_df.head(10)

/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

             feature   pearson  spearman  count
82    latency_us_p99  1.000000  1.000000   1575
83   latency_us_p999  1.000000  1.000000   1575
538  latency_p999_us  1.000000  1.000000   1575
96         io_us_p99  0.997134  0.991882   1575
97        io_us_p999  0.997134  0.991882   1575
537   latency_p95_us  0.959061  0.979070   1575
81    latency_us_p95  0.959061  0.979070   1575
80    latency_us_p90  0.951758  0.971300   1575
536   latency_p90_us  0.951758  0.971300   1575
95         io_us_p95  0.957327  0.970072   1575

In [11]:
# ===== 計算 Top-K 訊號與延遲的相關性（若存在） =====

# 初始化 Top-K 相關性表
topk_corr_df = pd.DataFrame()

# 若有主要延遲欄位且合併資料中有 Top-K 欄位
if latency_primary is not None and latency_primary in merged.columns:
    # 找出所有以 '_topk' 結尾的欄位（來自 topk_df 的欄位）
    topk_cols = [c for c in merged.columns if c.endswith('_topk')]
    
    # 儲存相關性結果
    rows = []
    
    # 對每個 Top-K 欄位計算與延遲的相關性
    for col in topk_cols:
        # 取出該欄位與延遲欄位的資料（移除遺失值）
        series = merged[[col, latency_primary]].apply(pd.to_numeric, errors='coerce').dropna()
        
        if series.empty:
            continue
        
        # 計算 Spearman 相關係數
        # （Top-K 特徵通常是排名或計數，適合用 Spearman）
        rows.append({
            'feature': col,  # 特徵名稱
            'spearman': series[col].corr(series[latency_primary], method='spearman'),
            'count': len(series),  # 有效資料筆數
        })
    
    # 若有結果，則建立表格並儲存
    if rows:
        # 依 Spearman 係數排序（由高到低）
        topk_corr_df = pd.DataFrame(rows).sort_values('spearman', ascending=False)
        
        # 儲存表格
        topk_corr_df.to_csv(out_tables / f'latency_topk_correlation_{latency_primary}.csv', index=False)

# 顯示相關性最高的前 10 個 Top-K 特徵
topk_corr_df.head(10)

/home/gt/miniconda3/envs/diskann/lib/python3.13/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

                           feature  spearman  count
5     topk_expanded_degree_p0_topk -0.002291   1575
4   topk_expanded_degree_mean_topk -0.002291   1575
6     topk_expanded_degree_p1_topk -0.002291   1575
9    topk_expanded_degree_p25_topk -0.002291   1575
8    topk_expanded_degree_p10_topk -0.002291   1575
7     topk_expanded_degree_p5_topk -0.002291   1575
11   topk_expanded_degree_p75_topk -0.002291   1575
12   topk_expanded_degree_p90_topk -0.002291   1575
13   topk_expanded_degree_p95_topk -0.002291   1575
10   topk_expanded_degree_p50_topk -0.002291   1575